---
title: "CH1"
output:
  word_document:
    fig_width: 10
    fig_height: 7
    reference_docx: mystyles.docx 
---


```{r warning=F,message=F}
#install.packages("heplots")

require(heplots)
 require(mosaic)
 data(MockJury)
#View(MockJury)
head(MockJury)
tail(MockJury)
#help(MockJury)
summary(MockJury)
par(mfrow=c(1,2)) #Makes one row and two columns of plot panels
hist(MockJury$Years,xlab="Years",labels=T,main="Histogram of Years")
boxplot(MockJury$Years,ylab="Years",main="Boxplot of Years")
par(mfrow=c(1,1)) #Returns to making one graph at a time

hist(MockJury$Years,freq=F,xlab="Years",main="Histogram of Years")
lines(density(MockJury$Years),lwd=3,col="red")

hist(MockJury$Years,freq=F,xlab="Years",main="Histogram of Years with density curve and rug")
lines(density(MockJury$Years),lwd=3,col="red")
set.seed(3234)
rug(jitter(MockJury$Years),col="blue",lwd=2)

boxplot(Years~Attr,data=MockJury)

require(beanplot)
beanplot(Years~Attr,data=MockJury,log="",col="bisque",method="jitter")

mean(Years~Attr,data=MockJury)
sd(Years~Attr,data=MockJury)
favstats(Years~Attr,data=MockJury)



MockJury$NotBeautiful <- MockJury$Attr!="Beautiful"
MockJury$NotBeautiful
data.frame(MockJury$Attr,MockJury$NotBeautiful)

MockJury[5,]
MockJury[5,3]

MockJury2 <- MockJury[MockJury$NotBeautiful,]
summary(MockJury2$Attr)

MockJury2$Attr <- factor(MockJury2$Attr) 

summary(MockJury2$Attr)

par(mfrow=c(1,2))
boxplot(Years~Attr,data=MockJury2)
beanplot(Years~Attr,data=MockJury2,log="",col="bisque",method="jitter")
mean(Years~Attr,data=MockJury2)

diffmean(Years ~ Attr, data=MockJury2)

 require(scatterplot3d)
par(mfrow=c(1,2))
 x=sort(rep(c(1,2),1000))
 y=rep(seq(from=-10,to=20,length.out=1000),2)
 z=dnorm(y,mean=5,sd=2)
 s3d <- scatterplot3d(x=x,y=y,z=z,pch=20,xlab="Group",angle=60,type="p",box=F,axis=F)
 text(s3d$xyz.convert(1.4, 15, 0.07),labels=expression(mu[1]==mu[2]))
 
 z=dnorm(y,mean=c(rep(0,1000),rep(10,1000)),sd=2)
 s3d <- scatterplot3d(x=x,y=y,z=z,pch=20,xlab="Group",angle=60,type="p",box=F,axis=F)
 text(s3d$xyz.convert(1.4, 15, 0.07),labels=expression(mu[1]!=mu[2]))
 
 set.seed(1234)
 Perm1 <- with(MockJury2,data.frame(Years,Attr,PermutedAttr=shuffle(Attr)))
 Perm1
 
 beanplot(Years~Attr,data=Perm1,log="",col="bisque",method="jitter",main="Original data")
 beanplot(Years~PermutedAttr,data=Perm1,log="",col="bisque",method="jitter",main="Permuted group labels")
 mean(Years ~ PermutedAttr, data=Perm1)
 diffmean(Years ~ PermutedAttr, data=Perm1)
 
 B<-5
 for (b in (1:B)){
   print(b)
   }
 
 
 Ts<-diffmean(Years ~ shuffle(Attr), data=MockJury2)
 Ts
 for (b in (1:B)){
   Ts<-diffmean(Years ~ shuffle(Attr), data=MockJury2)
   print(Ts)
   }
 
 Tstar<-matrix(NA,nrow=B)
 Tstar
 for (b in (1:B)){
   Tstar[b]<-diffmean(Years ~ shuffle(Attr), data=MockJury2)
   }
 Tstar
 
 
 B<- 1000
 Tstar<-matrix(NA,nrow=B)
 for (b in (1:B)){
   Tstar[b]<-diffmean(Years ~ shuffle(Attr), data=MockJury2)
   }
 hist(Tstar,labels=T)
 plot(density(Tstar),main="Density curve of Tstar")
 favstats(Tstar)
 
 Tobs<-1.837
 hist(Tstar,labels=T)
 abline(v=Tobs,lwd=2,col="red")
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=Tobs,lwd=2,col="red")
 
 pdata(Tstar,Tobs,lower.tail=F)
 pdata(Tstar,-Tobs,lower.tail=T)
 
 hist(Tstar,labels=T)
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 

 pdata(abs(Tstar),abs(Tobs),lower.tail=F)
 
 par(mfrow=c(1,2))
 Tobs <- t.test(Years ~ Attr, data=MockJury2,var.equal=T)$statistic
 Tobs
 Tstar<-matrix(NA,nrow=B)
 for (b in (1:B)){
   Tstar[b]<-t.test(Years ~ shuffle(Attr), data=MockJury2,var.equal=T)$statistic
   }
 hist(Tstar,labels=T)
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 
 pdata(abs(Tstar),abs(Tobs),lower.tail=F)
 
 t.test(Years ~ Attr, data=MockJury2,var.equal=T)
 
 
 xa<-seq(from=-7,to=7,length.out=300)
 par(mfrow=c(1,1))
 plot(xa,dt(xa,df=2),type="l",xlab="t-values",ylab="Density",lwd=4,ylim=c(0,0.39),main="Plot of three different t-distributions and the normal curve")
 lines(xa,dt(xa,df=10),lwd=3,col="grey")
 lines(xa,dt(xa,df=20),lwd=2)
 lines(xa,dnorm(xa),lty=2,lwd=2,col="blue")
 legend("left",legend=c("t(2)","t(10)","t(20)","Normal"),col=c("black","grey","black","blue"),lty=c(1,1,1,2),lwd=c(4,3,2,2))
 
 plot(density(Tstar),main="Permutation and t(73) distributions",xlab="T=t-statistic",lwd=2)
 x<-seq(from=-4,to=4,length.out=100)
 lines(x,dt(x,df=73),col="red",lty=2,lwd=2)
 legend("left",legend=c("Permutation","t(73)"),col=c("black","red"),lty=c(1,2),lwd=c(1,2))
 
 
 x<-seq(from=-4,to=4,length.out=20)
 plot(x,dt(x,df=73),col="red",lty=2,lwd=2,type="l",xlab="t-values",ylab="Density",main="Plot of t(73) distribution" )
 abline(v=-2.1702)
 abline(v=2.1702)
 
 pt(-2.1702,df=73,lower.tail=T)
 2*pt(-2.1702,df=73,lower.tail=T)
 2*pt(abs(-2.1702),df=73,lower.tail=F)


```


```{r warning=F,message=F}
s217<-read.csv("http://www.math.montana.edu/courses/s217/documents/s217.csv",header=T)
 require(mosaic)
 par(mfrow=c(1,2))
 boxplot(GPA~Sex,data=s217)
 require(beanplot)
 beanplot(GPA~Sex,data=s217,log="",col="lightblue",method="jitter")
 
 mean(GPA~Sex,data=s217)
 favstats(GPA~Sex,data=s217)
 
 diffmean(GPA~Sex,data=s217)
 t.test(GPA~Sex,data=s217,var.equal=T)
 
 
 Tobs <- t.test(GPA~Sex,data=s217,var.equal=T)$statistic
 Tobs
 Tstar<-matrix(NA,nrow=B)
 for (b in (1:B)){
   Tstar[b]<-t.test(GPA~shuffle(Sex),data=s217,var.equal=T)$statistic
   }
 hist(Tstar,labels=T)
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=c(-1,1)*Tobs,lwd=2,col="red")
 pdata(abs(Tstar),abs(Tobs),lower.tail=F)

```


Bootstrapping code
```{r}

MockJury_BTS<-resample(MockJury2,groups=MockJury2$Attr)
table(as.numeric(MockJury_BTS$orig.id))
table(MockJury_BTS$Attr)
MockJury_BTS2<-resample(MockJury2,groups=MockJury2$Attr)
table(as.numeric(MockJury_BTS2$orig.id))

cs1<-table(as.vector(table(as.numeric(MockJury_BTS$orig.id))))
n0s<-75-sum(cs1)

cs1_final<-table(c(rep(0,n0s),as.vector(table(as.numeric(MockJury_BTS$orig.id)))))

cs2<-table(as.vector(table(as.numeric(MockJury_BTS2$orig.id))))
n0s<-75-sum(cs2)

cs2_final<-table(c(rep(0,n0s),as.vector(table(as.numeric(MockJury_BTS2$orig.id)))))

par(mfrow=c(1,2))
plot(cs1_final,ylab="Counts of number of times of re-sampling",main="Bootstrap sample 1",xlab="Times re-sampled")
plot(cs2_final,ylab="Counts of number of times of re-sampling", main="Bootstrap sample 2",xlab="Times re-sampled")
 
 Tobs <- diffmean(Years ~ Attr, data=MockJury2); Tobs
 B<- 1000
 Tstar<-matrix(NA,nrow=B)
 for (b in (1:B)){
    Tstar[b]<-diffmean(Years ~ Attr, data=resample(MockJury2,groups=MockJury2$Attr))
   }
 hist(Tstar,labels=T)
 abline(v=Tobs,col="red",lwd=2)
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=Tobs,col="red",lwd=2)
 favstats(Tstar)
 
 
 qdata(Tstar,.025)
 qdata(Tstar,.975)
 quantiles<-qdata(Tstar,c(.025,.975))
 quantiles
 hist(Tstar,labels=T)
 abline(v=quantiles$quantile,col="blue",lwd=3)
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=quantiles$quantile,col="blue",lwd=3)
 
 t.test(Years ~ Attr, data=MockJury2,var.equal=T)
 

 par(mfrow=c(1,1))
 x<-seq(from=-4,to=4,length.out=200)
 plot(x,dt(x,df=73),col="red",lty=2,lwd=3,type="l",xlab="t-values",ylab="Density",main="Plot of t(73) distribution" )
 abline(v=-2.1702,lwd=3)
 abline(v=2.1702,lwd=3)
 
 qt(.975,df=73)
 qt(.025,df=73)   
 
 x<-seq(from=-4,to=4,length.out=100)
 plot(x,dt(x,df=73),col="red",lty=2,lwd=2,type="l",xlab="t-values",ylab="Density",main="Plot of t(73) distribution" )
 abline(v=-1.9913)
 abline(v=1.9913)
 
 favstats(Years~Attr,data=MockJury2)
 sp <- sqrt(((38-1)*(2.8235^2)+(37-1)*(4.364^2))/(38+37-2))
 sp
 3.974-5.811+c(-1,1)*qt(.975,df=73)*sp*sqrt(1/38+1/37)
 qt(.975,df=73)*sp*sqrt(1/38+1/37)

```

```{r}
 s217<-read.csv("http://www.math.montana.edu/courses/s217/documents/s217.csv",header=T)
 require(mosaic)
 
 favstats(GPA~Sex,data=s217)
 sp <- sqrt(((37-1)*(0.4075^2)+(42-1)*(0.41518^2))/(37+42-2))
 sp
 3.338-3.0886+c(-1,1)*qt(.975,df=77)*sp*sqrt(1/37+1/42)
 qt(.975,df=77)*sp*sqrt(1/37+1/42)
 
  diffmean(GPA~Sex,data=s217)
 t.test(GPA~Sex,data=s217,var.equal=T)
 
  qt(.95,df=77) # For 90% confidence and 77 df
  qt(.995,df=77) #For 99% confidence and 77 df

  
t.test(GPA~Sex,data=s217,var.equal=T,conf.level=0.90)
t.test(GPA~Sex,data=s217,var.equal=T,conf.level=0.99)
 
 Tobs <- diffmean(GPA ~ Sex, data=s217); Tobs
 par(mfrow=c(1,2))
 B<- 1000
 Tstar<-matrix(NA,nrow=B)
 for (b in (1:B)){
   Tstar[b]<-diffmean(GPA ~ Sex, data=resample(s217,groups=s217$Sex))
   }
 
 qdata(Tstar,.05)
 qdata(Tstar,.95)
 quantiles<-qdata(Tstar,c(.05,.95))
 quantiles
 
 
 hist(Tstar,labels=T)
 abline(v=Tobs,col="red",lwd=2)
 abline(v=quantiles$quantile,col="blue",lwd=3,lty=2)
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=Tobs,col="red",lwd=2)
 abline(v=quantiles$quantile,col="blue",lwd=3,lty=2)
 
 favstats(Tstar)


```




