---
title: "CH56"
output:
  word_document:
    fig_height: 5
    fig_width: 8
    reference_docx: mystyles.docx
  pdf_document: default
---

```{r warning=F, message=F, echo=T}




#
set.seed(5678)

BB<- read.csv("http://www.math.montana.edu/courses/s217/documents/beersbac.csv")
#The EESEE story "Blood Alcohol Content" describes a study in which 16 student volunteers at The Ohio State University drank a randomly assigned number of cans of beer. Thirty minutes later, a police officer measured their blood alcohol content.
plot(BAC~Beers,data=BB)

x<-seq(from=0,to=20,length.out=20)
y<-(x-mean(x))^2
x<-c(x,5,15)
y<-c(y,220,220)

plot(x,y,col='blue',main="r=0")
require(psych) #install.packages("psych")
pairs.panels(BB,ellipses=F,smooth=F)

require(mosaic)
cor(BAC~Beers,data=BB)
cor(BB)

mtfires<- read.csv("http://www.math.montana.edu/courses/s217/documents/climateR2.csv")
mtfires$loghectacres<-log(mtfires$hectacres) #natural log transformation of area burned
mtfiresR<-mtfires[,-3] #Cuts the original hectacres data so only log-scale version in data.frame
cor(mtfiresR)
summary(mtfiresR)

require(psych) 
pairs.panels(mtfiresR,ellipses=F,scale=T,smooth=F,col=0)

#bozemantemps<- read.csv("http://dl.dropboxusercontent.com/u/77307195/tempMV.csv")

bozemantemps<- read.csv("http://www.math.montana.edu/courses/s217/documents/BozemanMeanMax.csv")

require(alr3)
data(ais)
aisR<-ais[,c("Ht","Hc","Bfat")]
summary(aisR)
pairs.panels(aisR,scale=T,ellipse=F,smooth=F,col=0)
cor(aisR)

  aisR[c(56,166),]
aisR2<-aisR[-c(56,166),] #Removes observations in rows 56 and 166

pairs.panels(aisR2,scale=T,ellipse=F,smooth=F,col=0)
```


```{r warning=F, message=F, echo=T,fig.height=6,fig.width=6}
require(corrplot)
corrplot.mixed(cor(aisR2), col=c("black", "orange"))

```

```{r warning=F, message=F, echo=T,fig.height=5,fig.width=8}

aisR2<-ais[-c(56,166),c("Ht","Hc","Bfat","Sex")]
require(car)
scatterplot(Hc~Ht|Sex,data=aisR2,pch=c(3,21),reg.line=F,smoother=F,boxplots="xy",main="Scatterplot of Height vs Hematocrit by Sex")


require(mosaic)
cor(Hc~Ht,data=aisR2[aisR2$Sex==0,]) #Males only
cor(Hc~Ht,data=aisR2[aisR2$Sex==1,]) #Females only

scatterplot(Hc~Bfat|Sex,data=aisR2,pch=c(3,21),reg.line=F,smoother=F,boxplots="xy",main="Scatterplot of Bodyfat vs Hematocrit by Sex")

cor(Hc~Bfat,data=aisR2[aisR2$Sex==0,]) #Males only
cor(Hc~Bfat,data=aisR2[aisR2$Sex==1,]) #Females only

scatterplot(Bfat~Ht|Sex,data=aisR2,pch=c(3,21),reg.line=F,smoother=F,boxplots="xy",main="Scatterplot of Height vs Bodyfat by Sex")

cor(Bfat~Ht,data=aisR2[aisR2$Sex==0,]) #Males only
cor(Bfat~Ht,data=aisR2[aisR2$Sex==1,]) #Females only


#Beers and BAC data set bootstrapping:
BB<- read.csv("http://www.math.montana.edu/courses/s217/documents/beersbac.csv")
require(mosaic)

Tobs <- cor(BAC~Beers,data=BB); Tobs

par(mfrow=c(1,2))
B<- 1000
Tstar<-matrix(NA,nrow=B)
for (b in (1:B)){
  Tstar[b]<-cor(BAC~Beers,data=resample(BB))
}
quantiles<-qdata(Tstar,c(.025,.975)) #95% Confidence Interval
quantiles

hist(Tstar,labels=T)
abline(v=Tobs,col="red",lwd=3)
abline(v=quantiles$quantile,col="blue",lty=2,lwd=3)

plot(density(Tstar),main="Density curve of Tstar")
abline(v=Tobs,col="red",lwd=3)
abline(v=quantiles$quantile,col="blue",lty=2,lwd=3)




#Regression material:
require(car)
scatterplot(BAC~Beers,data=BB,smooth=F)
require(psych)
pairs.panels(BB,ellipses=F,col=0)


#tree example
require(spuRs) #install.packages("spuRs")
data(ufc)
scatterplot(height.m~dbh.cm,data=ufc,smooth=F,reg.line=F)

ufc[168,]

cor(dbh.cm~height.m,data=ufc)
cor(dbh.cm~height.m,data=ufc[-168,])
```


```{r warning=F, message=F, echo=T,fig.height=7,fig.width=8}

Tobs <- cor(dbh.cm~height.m,data=ufc); Tobs

par(mfrow=c(2,1))
B<- 1000
Tstar<-matrix(NA,nrow=B)
for (b in (1:B)){
  Tstar[b]<-cor(dbh.cm~height.m,data=resample(ufc))
}
quantiles<-qdata(Tstar,c(.025,.975)) #95% Confidence Interval
quantiles

hist(Tstar,labels=T,main= "Bootstrap distribution of correlation with all data",xlim=c(0.6,0.9))
abline(v=Tobs,col="red",lwd=3)
abline(v=quantiles$quantile,col="blue",lty=2,lwd=3)

Tobs <- cor(dbh.cm~height.m,data=ufc[-168,]); Tobs

Tstar<-matrix(NA,nrow=B)
for (b in (1:B)){
  Tstar[b]<-cor(dbh.cm~height.m,data=resample(ufc[-168,]))
}
quantiles<-qdata(Tstar,c(.025,.975)) #95% Confidence Interval
quantiles

hist(Tstar,labels=T,main= "Bootstrap distribution of correlation without outlier",xlim=c(0.6,0.9))
abline(v=Tobs,col="red",lwd=3)
abline(v=quantiles$quantile,col="blue",lty=2,lwd=3)

```

```{r warning=F, message=F, echo=T,fig.height=5,fig.width=8}


#### Regression material####

BB<- read.csv("http://www.math.montana.edu/courses/s217/documents/beersbac.csv")
#The EESEE story "Blood Alcohol Content" describes a study in which 16 student volunteers at The Ohio State University drank a randomly assigned number of cans of beer. Thirty minutes later, a police officer measured their blood alcohol content.
require(car)
scatterplot(BAC~Beers,ylim=c(0,.2),xlim=c(0,9),data=BB,boxplot=F,main="Scatterplot with regression line",lwd=2,smooth=F)


abline(v=1:9,col="grey")
abline(h=c(0.05914,0.0771),col="blue",lty=2,lwd=2)


m1<-lm(BAC~Beers,data=BB)
m1
summary(m1)
anova(m1)

SStotal<-0.0233753+0.0058497
SSregression<-0.0233753
SSregression/SStotal

aisR2<-ais[-c(56,166),c("Ht","Hc","Bfat","Sex")]
scatterplot(Hc~Bfat,data=aisR2[aisR2$Sex==1,],smooth=F,main="Scatterplot of BodyFat vs Hematocrit for Female Athletes",ylab="Hc (% blood)",xlab="Body fat (% weight)")
m2<-lm(Hc~Bfat,data=aisR2[aisR2$Sex==1,]) #Results for Females 
summary(m2)
confint(m2)

s1<-seq(from=0, to=0.03,length.out=100)
ss1<-numeric(0)
for (j in (1:length(s1))){
  ss1[j]<-sum(lm(BAC~offset(Beers*s1[j]),data=BB)$residuals^2)
}
plot(s1,ss1,type="l",col="blue",lwd=2,xlab="Possible Slope Coefficients",ylab="Sum of squared residuals",main="Sums of squared residuals for different Slopes (Beers vs BAC data)")
abline(v=0.01796,col="red")

#require(tigerstats)
#require(manipulate)
#FindRegLine()

mtfires<- read.csv("http://www.math.montana.edu/courses/s217/documents/climateR2.csv")
mtfires$loghectacres<-log(mtfires$hectacres)

fire1<-lm(loghectacres~Temperature,data=mtfires)
summary(fire1)
confint(fire1,level=0.99)
qt(.995,df=21)

scatterplot(loghectacres~Temperature,data=mtfires,smoother=T,main="Scatterplot with regression line for Area burned vs Temperature")


#Two data sets with same regression line:

BB<- read.csv("http://www.math.montana.edu/courses/s217/documents/beersbac.csv")
#The EESEE story "Blood Alcohol Content" describes a study in which 16 student volunteers at The Ohio State University drank a randomly assigned number of cans of beer. Thirty minutes later, a police officer measured their blood alcohol content.
require(car)

m1<-lm(BAC~Beers,data=BB)

par(mfrow=c(1,3))
plot(BAC~Beers,ylim=c(-0.15,.35),xlim=c(1,9),data=BB,main="Real Data")
abline(a=m1$coef[1],b=m1$coef[2],col="green")

BBfake1=BB
BBfake1$BAC=fitted(m1)+residuals(m1)*5
plot(BAC~Beers,ylim=c(-0.15,.35),xlim=c(1,9),data=BBfake1,main="Fake Data")
m1<-lm(BAC~Beers,data=BBfake1)
abline(a=m1$coef[1],b=m1$coef[2],col="green")

BBfake2=BB
BBfake2$BAC=fitted(m1)+residuals(m1)/15
plot(BAC~Beers,ylim=c(-0.15,.35),xlim=c(1,9),data=BBfake2,main="Fake Data")
m1<-lm(BAC~Beers,data=BBfake2)
abline(a=m1$coef[1],b=m1$coef[2],col="green")

#Leverage and Influence explorations
BBfake3=BB
m1<-lm(BAC~Beers,data=BB)
par(mfrow=c(1,2))
id=rep(16,16)
id[3]=21; id[15]=5

par(mfrow=c(1,2))
plot(BAC~Beers,data=BB,pch=id,cex=1.3)
abline(a=m1$coef[1],b=m1$coef[2],col="green")
plot(m1,which=5,add.smooth=F,pch=id,cex=1.3)

BBfake3=BB
BBfake3[17,]=c(11,0.01)
m1o=lm(BAC~Beers,data=BB)
```

```{r warning=F, message=F, echo=T,fig.height=10,fig.width=8}

par(mfrow=c(4,2))
id1=rep(16,17)
id1[17]=8;
id2=rep(16,17)
id2[17]=1;


m1<-lm(BAC~Beers,data=BBfake3)
summary(m1)
plot(BAC~Beers,data=BBfake3,col=id2,pch=id1,main="Added (11,0.01), R-sq=0.24")
abline(a=m1o$coef[1],b=m1o$coef[2],col="blue",lty=2,lwd=2)
abline(a=m1$coef[1],b=m1$coef[2],col="green",lwd=2)
plot(m1,which=5,add.smooth=F,col=id2,pch=id1,main="Added (11,0.1)")


BBfake4=BB
BBfake4[17,]=c(11,0.19)
m1=lm(BAC~Beers,data=BBfake4)
summary(m1)
plot(BAC~Beers,data=BBfake4,col=id2,pch=id1,main="Added (11,0.19), R-sq=0.86")
abline(a=m1o$coef[1],b=m1o$coef[2],col="blue",lty=2,lwd=2)
abline(a=m1$coef[1],b=m1$coef[2],col="green",lwd=2)
plot(m1,which=5,add.smooth=F,col=id2,pch=id1,main="Added (11,0.19)")


BBfake5=BB
BBfake5[17,]=c(5,0.19)
m1=lm(BAC~Beers,data=BBfake5)
summary(m1)
plot(BAC~Beers,data=BBfake5,col=id2,pch=id1,main="Added (5,0.19), R-sq=0.57")
abline(a=m1o$coef[1],b=m1o$coef[2],col="blue",lty=2,lwd=2)
abline(a=m1$coef[1],b=m1$coef[2],col="green",lwd=2)
plot(m1,which=5,add.smooth=F,col=id2,pch=id1,main="Added (5,0.19)")

BBfake6=BB
BBfake6[17,]=c(5,0.01)
m1=lm(BAC~Beers,data=BBfake6)
summary(m1)
plot(BAC~Beers,data=BBfake6,col=id2,pch=id1,main="Added (5,0.01), R-sq=0.69")
abline(a=m1o$coef[1],b=m1o$coef[2],col="blue",lty=2,lwd=2)
abline(a=m1$coef[1],b=m1$coef[2],col="green",lwd=2)
plot(m1,which=5,add.smooth=F,col=id2,pch=id1,main="Added (5,0.1)")

plot(m1)
```
```{r warning=F, message=F, echo=T,fig.height=5,fig.width=8}
m1<-lm(BAC~Beers,data=BB)
par(mfrow=c(2,2))
plot(m1,add.smooth=F,main="Beers vs BAC")

require(spuRs) #install.packages("spuRs")
data(ufc)
require(car)
scatterplot(height.m~dbh.cm,data=ufc[-168,],smooth=F)
tree1<-lm(height.m~dbh.cm,data=ufc[-168,])
summary(tree1)
par(mfrow=c(2,2))
plot(tree1,add.smooth=F)

require(MASS)
data(geyser)
G2<-data.frame(Waiting=geyser$waiting[-1],Duration=geyser$duration[-299])
scatterplot(Waiting~Duration,data=G2,spread=F)
OF1<-lm(Waiting~Duration,data=G2)
summary(OF1)
par(mfrow=c(2,2))
plot(OF1)

par(mfrow=c(1,1))
set.seed(3456)

coef1<-m1$coefficients
Beersnew<-sort(rep(1:9,20))


e1_20<-rnorm(n=length(Beersnew),0,sd=0.02)
e1_20<-e1_20-mean(e1_20)
y1_20<-coef1[1]+coef1[2]*Beersnew+e1_20
plot(y1_20~I(Beersnew-0.05),ylim=c(-.1,0.27),pch=16,ylab="Simulated BACs",xlab="Beers")
abline(coef1,col="khaki",lwd=2)
e2_20<-rnorm(n=length(Beersnew),mean=0,sd=0.06)
e2_20<-e2_20-mean(e2_20)
y2_20<-coef1[1]+coef1[2]*Beersnew+e2_20
points(y2_20~I(Beersnew+.05),ylim=c(0,0.25),pch=17,col="orange")

legend("topleft",c("Residual SE=0.02","Residual SE=0.06"),pch=c(16,17),col=c("black","orange"),cex=1.1)



```


```{r warning=F, message=F, echo=T,fig.height=5,fig.width=8}

#Bozeman temps example: Update from NOAA's National Centers for Environmental Information (http://www.ncdc.noaa.gov/cdo-web/) 
#bozemantemps<- read.csv("http://dl.dropboxusercontent.com/u/77307195/tempMV.csv") #OLD VERSION
#bozemantemps$Year<-1900:2008

#New version:

bozemantemps<- read.csv("http://www.math.montana.edu/courses/s217/documents/BozemanMeanMax.csv")
summary(bozemantemps)
length(bozemantemps$Year) #Some years are missing (1905, 1906, 1948, 1950,1995)
require(car)
scatterplot(meanmax~Year,data=bozemantemps,ylab="Mean Maximum Temperature (degrees F)",spread=F,main="Scatterplot of Bozeman Yearly Average Max Temperatures")
temp1<-lm(meanmax~Year, data=bozemantemps)
par(mfrow=c(2,2))
plot(temp1,add.smooth=F)

summary(temp1)

2*pt(11.02,df=107,lower.tail=F)

confint(temp1)

require(effects)
plot(allEffects(temp1,xlevels=list(Year=bozemantemps$Year)),grid=T)

bozemantemps$Year2<-bozemantemps$Year-1901
summary(bozemantemps$Year2)

temp2<-lm(meanmax~Year2,data=bozemantemps)
summary(temp2)
confint(temp2)

require(mosaic)
Tobs <- lm(meanmax~Year,data=bozemantemps)$coef[2]
Tobs
par(mfrow=c(1,2))
B<- 1000
Tstar<-matrix(NA,nrow=B)
for (b in (1:B)){
  Tstar[b]<-lm(meanmax~shuffle(Year),data=bozemantemps)$coef[2]
}
hist(Tstar,xlim=c(-1,1)*Tobs)
abline(v=c(-1,1)*Tobs,col="red",lwd=3)
plot(density(Tstar),main="Density curve of Tstar",xlim=c(-1,1)*Tobs)
abline(v=c(-1,1)*Tobs,col="red",lwd=3)


pdata(abs(Tstar),abs(Tobs),lower.tail=F)

set.seed(12345)
Tobs <- lm(meanmax~Year,data=bozemantemps)$coef[2]
Tobs
par(mfrow=c(1,2))
B<- 1000
Tstar<-matrix(NA,nrow=B)
for (b in (1:B)){
  Tstar[b]<-lm(meanmax~Year,data=resample(bozemantemps))$coef[2]
}

quantiles<-qdata(Tstar,c(.025,.975))
 quantiles
 hist(Tstar,labels=T)
 abline(v=Tobs,col="red",lwd=2)
 abline(v=quantiles$quantile,col="blue",lwd=3)
 plot(density(Tstar),main="Density curve of Tstar")
 abline(v=Tobs,col="red",lwd=2)
 abline(v=quantiles$quantile,col="blue",lwd=3)

#Four plots for permutation array
set.seed(1667)


par(mfrow=c(2,2))
d1<-bozemantemps
d1$Year<-shuffle(d1$Year)
plot(meanmax~Year,data=d1,xlab="Year",ylab="Maximum Temperature",main="(a)")
abline(lm(meanmax~Year,data=d1)$coefficients,lwd=2,col="red")

d1<-bozemantemps
d1$Year<-shuffle(d1$Year)
plot(meanmax~Year,data=d1,xlab="Year",ylab="Maximum Temperature",main="(b)")
abline(lm(meanmax~Year,data=d1)$coefficients,lwd=2,col="red")



d1<-bozemantemps
d1$Year<-shuffle(d1$Year)
plot(meanmax~Year,data=bozemantemps,xlab="Year",ylab="Maximum Temperature",main="(c)")
abline(lm(meanmax~Year,data=bozemantemps)$coefficients,lwd=2,col="red")

set.seed(97531)

d1<-bozemantemps
d1$Year<-shuffle(d1$Year)
plot(meanmax~Year,data=d1,xlab="Year",ylab="Maximum Temperature",main="(d)")
abline(lm(meanmax~Year,data=d1)$coefficients,lwd=2,col="red")



bozemantemps$meanmaxC<- (bozemantemps$meanmax-32)*(5/9)
temp3<-lm(meanmaxC~Year2, data=bozemantemps)
summary(temp1)
summary(temp3)

par(mfrow=c(1,2))
plot(meanmax~Year,data=bozemantemps,xlab="Year",ylab="degrees F",main="degrees F and Year")
abline(lm(meanmax~Year,data=bozemantemps)$coefficients,lwd=2,col="steelblue")

plot(meanmaxC~Year2,data=bozemantemps,xlab="Years since 1901",ylab="degrees C",main="degrees C and Years since 1901")
abline(temp3$coefficients,lwd=2,col="steelblue")


par(mfrow=c(1,1))

mtfires<- read.csv("http://www.math.montana.edu/courses/s217/documents/climateR2.csv")
mtfires$loghectacres<-log(mtfires$hectacres)

par(mfrow=c(1,2))
plot(hectacres~Temperature,data=mtfires, main="(a)",ylab="Hectacres",pch=16)
plot(loghectacres~Temperature,data=mtfires, main="(b)",ylab="log-Hectacres",pch=16)

require(spuRs) #install.packages("spuRs")
data(ufc)
require(car)
scatterplot(height.m~dbh.cm,data=ufc[-168,],main="Tree height vs tree diameter",smooth=T,spread=F)
scatterplot(log(height.m)~dbh.cm,data=ufc[-168,],smooth=T,spread=F,main="log-Tree height vs tree diameter")
scatterplot(height.m~log(dbh.cm),data=ufc[-168,],smooth=T,spread=F,main="Tree height vs log-tree diameter")
scatterplot(log(height.m)~log(dbh.cm),data=ufc[-168,],smooth=T,spread=F,main="log-Tree height vs log-tree diameter")

require(car)
data(UN)
par(mfrow=c(2,2))
plot(infant.mortality~gdp,data=UN,pch=16,col="coral",xlab="GDP",ylab="Infant deaths/1000 births",main="(a) Infant Mortality vs GDP")

plot(log(infant.mortality)~gdp,data=UN,pch=16,col="coral",xlab="GDP",ylab="log-Infant deaths/1000 births",main="(b) log-Infant Mortality vs GDP")

plot(infant.mortality~log(gdp),data=UN,pch=16,col="coral",xlab="log-GDP",ylab="Infant deaths/1000 births",main="(c) Infant Mortality vs log-GDP")

plot(log(infant.mortality)~log(gdp),data=UN,pch=16,col="coral",xlab="log-GDP",ylab="log-Infant deaths/1000 births",main="(d) log-Infant Mortality vs log-GDP")

log(-1)
log(0)

exp(0.4)


par(mfrow=c(1,2))
plot(loghectacres~Temperature,data=mtfires, main="(a)",ylab="log-Hectacres",pch=16,col="salmon")
firem<-lm(loghectacres~Temperature,data=mtfires)
abline(lm(loghectacres~Temperature,data=mtfires),lwd=2,col="darkred")
plot(hectacres~Temperature,data=mtfires, main="(b)",ylab="Hectacres",pch=16,col="salmon")
t1<-seq(from=53,to=60,length.out=30)
lines(exp(firem$coef[1]+firem$coef[2]*t1)~t1,lwd=2,col="darkred")

data(UN)
ID1<-lm(infant.mortality~log(gdp),data=UN)
summary(ID1)

-16.6*log(2)
par(mfrow=c(2,2))
plot(ID1)

ID2<-lm(log(infant.mortality)~log(gdp),data=UN)
summary(ID2)

par(mfrow=c(2,2))
plot(ID2)

par(mfrow=c(1,2))

plot(infant.mortality~log(gdp),data=UN,pch=16,col="coral",xlab="log-GDP",ylab="Infant deaths/1000 births",main="(a) Infant Mortality vs log-GDP")
abline(ID1$coef,lwd=2,col="slateblue4")

plot(infant.mortality~gdp,data=UN,pch=16,col="coral",xlab="GDP",ylab="Infant deaths/1000 births",main="(b) Infant Mortality vs GDP")

gdp1<-seq(from=30,to=42416,length.out=100)
lines(ID1$coef[1]+ID1$coef[2]*log(gdp1)~gdp1,lwd=2,col="slateblue4")



par(mfrow=c(1,2))

plot(log(infant.mortality)~log(gdp),data=UN,pch=16,col="coral",xlab="log-GDP",ylab="log-Infant deaths/1000 births",main="(a) log-Infant Mortality vs log-GDP")
abline(ID2$coef,lwd=2,col="slateblue3")

plot(infant.mortality~gdp,data=UN,pch=16,col="coral",xlab="GDP",ylab="Infant deaths/1000 births",main="(b) Infant Mortality vs GDP")

gdp1<-seq(from=30,to=42416,length.out=100)
lines(exp(ID2$coef[1]+ID2$coef[2]*log(gdp1))~gdp1,lwd=2,col="slateblue3")




#############CI and PI code################
 BB<- read.csv("http://www.math.montana.edu/courses/s217/documents/beersbac.csv")
 m1<-lm(BAC~Beers,data=BB)
 predict(m1,newdata=data.frame(Beers=8))

 predict(m1,newdata=data.frame(Beers=8),se.fit=T)

 predict(m1,newdata=data.frame(Beers=8),interval="confidence")
 
 predict(m1,newdata=data.frame(Beers=8),interval="prediction")
 
 qt(.975,df=14) #t* multiplier for 95% CI or 95% PI
 
 0.131+c(-1,1)*2.1448*0.0092
 
 sqrt(0.0092^2+0.02044^2)
 
 0.131+c(-1,1)*2.1448*0.0224
 
 
 confint(m1)
 
 beerf<-seq(from=0,to=10,length.out=30)
BBCI<-data.frame(predict(m1,newdata= data.frame(Beers=beerf),interval="confidence"))
head(BBCI)
BBPI<-data.frame(predict(m1,newdata=data.frame(Beers=beerf),interval="prediction"))
head(BBPI)

par(mfrow=c(1,1))
plot(BAC~Beers,data=BB,xlab="Beers", ylab="BAC",pch=20,col="gold4", main="Scatterplot of estimated regression line with 95% CI and PI")
 lines(beerf,BBCI$fit,col="blue",lwd=3)
 lines(beerf,BBCI$lwr,col="red",lty=2,lwd=3)
 lines(beerf,BBCI$upr,col="red",lty=2,lwd=3)
 lines(beerf,BBPI$lwr,col="grey",lty=3,lwd=3)
 lines(beerf,BBPI$upr,col="grey",lty=3,lwd=3)
legend("topleft", c("Estimate", "CI","PI"),lwd=3,lty=c(1,2,3),col = c("blue", "red","grey"))


#CI and PI for yearly temperature data

temp1<-lm(meanmax~Year, data=bozemantemps)
 Yearf<-seq(from=1901,to=2014,length.out=75)
 
TCI<-data.frame(predict(temp1,newdata= data.frame(Year=Yearf),interval="confidence"))
head(TCI)
TPI<-data.frame(predict(temp1,newdata=data.frame(Year=Yearf),interval="prediction"))
head(TPI)

plot(meanmax~Year,data=bozemantemps,xlab="Year", ylab="degrees F",pch=20,col="darkgreen", main="Scatterplot of estimated regression line with 95% CI and PI")
 lines(Yearf,TCI$fit,col="blue",lwd=3)
 lines(Yearf,TCI$lwr,col="red",lty=2,lwd=3)
 lines(Yearf,TCI$upr,col="red",lty=2,lwd=3)
 lines(Yearf,TPI$lwr,col="grey",lty=3,lwd=3)
 lines(Yearf,TPI$upr,col="grey",lty=3,lwd=3)
legend("topleft", c("Estimate", "CI","PI"),lwd=3,lty=c(1,2,3),col = c("blue", "red","grey"))
 
 
 predict(temp1,newdata=data.frame(Year=2015),interval="confidence")
 predict(temp1,newdata=data.frame(Year=2015),interval="prediction")

 
 predict(temp1,newdata=data.frame(Year=2050),interval="confidence")
 predict(temp1,newdata=data.frame(Year=2050),interval="prediction")

 
 
#################################################################################


#Maybe next time or for quizzes?
require(DMwR)
data(algae)
pairs.panels(algae)

require(mlmRev)
data(Mmmec)
data(star) #Revisit for MLR?



require(aplpack)

bagplot.pairs(trees,col.baghull="green", col.loophull="lightgreen")


require(corrplot)
#data(Leaves)
#corrplot.mixed(Leaves)

#Later for exploring correlations

require(gpairs)

gpairs(trees,upper.pars=list(scatter="corrgram"))

require(psych)
pairs.panels(trees)

pairs.panels(trees,lm=T,smooth=T,cor=F)

pairs.panels(trees,lm=T,ellipses=F,scale=T)
```
