---
title: "Chapter2 Scratch"
author: "Greta Linse Peterson"
date: "June 4, 2017"
output: html_document
---









Load the </span>
``HELPrct``  data set from the </span>
``mosaicData``  package (you need to install the </span>
``mosaicData``  package once to be able to load it). The HELP study was a clinical trial for adult inpatients recruited from a
detoxification unit. Patients with no primary care physician were randomly
assigned to receive a multidisciplinary assessment and a brief motivational
intervention or usual care and various outcomes were observed. Two of the
variables in the dataset are </span>

``sex`` , a factor with levels male and female and </span>
``daysanysub``  which is the time (in days) to firstuse of any substance post-detox. We are interested in the difference in mean
number of days to first use of any substance post-detox between males and
females. There are some missing responses and the following code will produce </span>

``favstats``  with the missing values and thenprovide a data set that for complete observations by applying the </span>

``na. omit``  function that removes anyobservations with missing values. 

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
require(mosaicData) #load the dataset

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
data(HELPrct)

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
HELPrct2&lt;-HELPrct[, c("daysanysub", "sex")]
#Just focus on two variables

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
HELPrct3&lt;-na. omit(HELPrct2) #Removes subjects with missing

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
favstats(daysanysub~sex, data = HELPrct2)

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>
favstats(daysanysub~sex, data = HELPrct3)

</span>


style='font-size:10. 0pt;mso-bidi-font-size:12. 0pt;line-height:107%;font-family:"Lucida Console"'>

&nbsp;
</span>


1. 1. Based on the results provided, 
how many observations were missing for males and females? Missing values here
likely mean that the subjects didn?t use any substances post-detox in the time
of the study but might have at a later date ? the study just didn?t run long
enough. This is called  ***censoring*** . What is the problem withthe numerical summaries here if the missing responses were all something larger
than the largest observation?

</span>


1. 2. Make a beanplot and a boxplot of
</span>

``daysanysub``  ~ </span>
``sex``  using the </span>
``HELPrct3``  data set created above. Compare thedistributions, recommending parametric or nonparametric inferences. 

</span>

1. 3. Generate the permutation results
and write out the 6+ steps of the hypothesis test, making sure to note the
numerical value of observed test statistic you are using and include a
discussion of the scope of inference. 

</span>


1. 4. Interpret the p-value for these
results. 

</span>


1. 5. Generate the parametric </span>

``t. test``  results, reporting the test-statistic, its distribution under the null hypothesis, and compare the p-value to those
observed using the permutation approach. 

</span>


1. 6. Make and interpret a 95%
bootstrap confidence interval for the difference in the means. 

</span>



&nbsp;
</span>


</div>


<hr align=left size=1 width="33%">


<![endif]>


<div style='mso-element:footnote' id=ftn1>


<a style='mso-footnote-id:ftn1' href="#_ftnref1"name="_ftn1" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[1]</span>
</span>
<![endif]>
</span>
</span>
</a>

">
http://fivethirtyeight. com/</a>
. </p>


</div>


<div style='mso-element:footnote' id=ftn2>


<a style='mso-footnote-id:ftn2' href="#_ftnref2"name="_ftn2" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[2]</span>
</span>
<![endif]>
</span>
</span>
</a>
 </p>


</div>


<div style='mso-element:footnote' id=ftn3>


<a style='mso-footnote-id:ftn3' href="#_ftnref3"name="_ftn3" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[3]</span>
</span>
<![endif]>
</span>
</span>
</a>
 If
you?ve taken calculus, you will know that the curve is being constructed so
that the integral from -&#8734; to &#8734; is 1. If you don?t know calculus, 
think of a rectangle with area of 1 based on its height and width. These cover
the same area but the top of the region wiggles. </p>


</div>


<div style='mso-element:footnote' id=ftn4>


<a style='mso-footnote-id:ftn4' href="#_ftnref4"name="_ftn4" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[4]</span>
</span>
<![endif]>
</span>
</span>
</a>

Jittering typically involves adding random variability to each observation that
is uniformly distributed in a range determined based on the spacing of the
function, the results will change. For more details, type ``help(jitter)``  in R. </p>


</div>


<div style='mso-element:footnote' id=ftn5>


<a style='mso-footnote-id:ftn5' href="#_ftnref5"name="_ftn5" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[5]</span>
</span>
<![endif]>
</span>
</span>
</a>
 <spanstyle='mso-bidi-font-size:12. 0pt'>
Remember the bell-shaped curve youencountered in introductory statistics? If not, you can see some at </span>
<a
href="https://en. wikipedia. org/wiki/Normal_distribution">
https://en. wikipedia. org/wiki/Normal_distribution</span>
</a>


</span>


</div>


<div style='mso-element:footnote' id=ftn6>


<a style='mso-footnote-id:ftn6' href="#_ftnref6"name="_ftn6" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[6]</span>
</span>
<![endif]>
</span>
</span>
</a>
 Well, 
you can use other colors (try "lightblue" for example), but I think bisque
looks nice in these plots. </p>


</div>


<div style='mso-element:footnote' id=ftn7>


<a style='mso-footnote-id:ftn7' href="#_ftnref7"name="_ftn7" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[7]</span>
</span>
<![endif]>
</span>
</span>
</a>

The hypothesis of no difference that is typically generated in the hopes of
being rejected in favor of the alternative hypothesis which contains the sort
of difference that is of interest in the application. </p>


</div>


<div style='mso-element:footnote' id=ftn8>


<a style='mso-footnote-id:ftn8' href="#_ftnref8"name="_ftn8" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[8]</span>
</span>
<![endif]>
</span>
</span>
</a>

The null model is the statistical model that is implied by the chosen null
hypothesis. Here, a null hypothesis of no difference translates to having a
model with the same mean for both groups. </p>


</div>


<div style='mso-element:footnote' id=ftn9>


<a style='mso-footnote-id:ftn9' href="#_ftnref9"name="_ftn9" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[9]</span>
</span>
<![endif]>
</span>
</span>
</a>
 We?ll
more common usage below; while the code to generate ``Perm1``  is provided, it isn?t something to worry about
right now. </p>


</div>


<div style='mso-element:footnote' id=ftn10>


<a style='mso-footnote-id:ftn10' href="#_ftnref10"name="_ftn10" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[10]</span>
</span>
<![endif]>
</span>
</span>
</a>

P-values are the probability of obtaining a result as extreme as or more
extreme than we observed given that the null hypothesis is true. </p>


</div>


<div style='mso-element:footnote' id=ftn11>


<a style='mso-footnote-id:ftn11' href="#_ftnref11"name="_ftn11" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[11]</span>
</span>
<![endif]>
</span>
</span>
</a>

We often say "under" in statistics and we mean "given that the following is
true". </p>


</div>


<div style='mso-element:footnote' id=ftn12>


<a style='mso-footnote-id:ftn12' href="#_ftnref12"name="_ftn12" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[12]</span>
</span>
<![endif]>
</span>
</span>
</a>

This is a fancy way of saying "in advance", here in advance of seeing the
observations. </p>


</div>


<div style='mso-element:footnote' id=ftn13>


<a style='mso-footnote-id:ftn13' href="#_ftnref13"name="_ftn13" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[13]</span>
</span>
<![endif]>
</span>
</span>
</a>

Statistically, a conservative method is one that provides less chance of
rejecting the null hypothesis in comparison to some other method or less than
some pre-defined standard. </p>


</div>


<div style='mso-element:footnote' id=ftn14>


<a style='mso-footnote-id:ftn14' href="#_ftnref14"name="_ftn14" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[14]</span>
</span>
<![endif]>
</span>
</span>
</a>

We?ll leave the discussion of the CLT to your previous stat coursework or an
internet search. Remember that it has something to do with distributions
looking more normal as the sample size increases. </p>


</div>


<div style='mso-element:footnote' id=ftn15>


<a style='mso-footnote-id:ftn15' href="#_ftnref15"name="_ftn15" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[15]</span>
</span>
<![endif]>
</span>
</span>
</a>
 <spanstyle='font-size:11. 0pt;mso-bidi-font-size:12. 0pt'>
On exams, you will be askedto describe the area of interest, sketch a picture of the area of interest, 
and/or note the distribution you would use. </span>


</div>


<div style='mso-element:footnote' id=ftn16>


<a style='mso-footnote-id:ftn16' href="#_ftnref16"name="_ftn16" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[16]</span>
</span>
<![endif]>
</span>
</span>
</a>

In some studies, the same subject might be measured in both conditions and this
violates the assumptions of this procedure. </p>


</div>


<div style='mso-element:footnote' id=ftn17>


<a style='mso-footnote-id:ftn17' href="#_ftnref17"name="_ftn17" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[17]</span>
</span>
<![endif]>
</span>
</span>
</a>

also used here. It really isn?t important but makes sure the output of ``table``  is sorted by observation
number by first converting the *orig. id*variable into a numeric vector. </p>

</div>


<div style='mso-element:footnote' id=ftn18>


<a style='mso-footnote-id:ftn18' href="#_ftnref18"name="_ftn18" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[18]</span>
</span>
<![endif]>
</span>
</span>
</a>

There are actually many ways to use this information to make a confidence
interval. We are using the simplest method called that is called the
"percentile" method. </p>


</div>


<div style='mso-element:footnote' id=ftn19>


<a style='mso-footnote-id:ftn19' href="#_ftnref19"name="_ftn19" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[19]</span>
</span>
<![endif]>
</span>
</span>
</a>

When hypothesis tests "work well" they have high power to detect differences
while having Type I error rates that are close to what we chose a priori. When
confidence intervals "work well", they contain the true parameter value in
repeated random samples at around the selected confidence level. </p>


</div>


<div style='mso-element:footnote' id=ftn20>


<a style='mso-footnote-id:ftn20' href="#_ftnref20"name="_ftn20" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[20]</span>
</span>
<![endif]>
</span>
</span>
</a>

We rounded the means a little and that caused the small difference in results. </p>


</div>


<div style='mso-element:footnote' id=ftn21>


<a style='mso-footnote-id:ftn21' href="#_ftnref21"name="_ftn21" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[21]</span>
</span>
<![endif]>
</span>
</span>
</a>

You can correctly call octothorpes *number*symbols or, in the twitter verse, *hashtags*. For more on this symbol, see <a href="http://blog. dictionary. com/octothorpe/">
http://blog. dictionary. com/octothorpe/</a>
. 
I usually call them number symbols too. </p>


</div>


</div>


** 

</html>
