---
output:
  html_document: default
  pdf_document: default
---

#One-Way ANOVA






</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``color:red'>
MODELNAME`` 
``&lt;-lm(<span style='color:red'>
Y`` ~<spanmargin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Probablythe most frequently used command in R. 

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Hereit is used to fit the reference-coded One-Way ANOVA model with Y as the response
variable and X as the grouping variable, storing the estimated model object in
MODELNAME. 

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``color:red'>
MODELNAME`` 
``&lt;-lm(<span style='color:red'>
Y`` ~<spanmargin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Fitsthe cell means version of the One-Way ANOVA model. 

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``summary`` 
(</span>
``MODELNAME)`` 

</span>

margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Generatesmodel summary information including the estimated model coefficients, SEs, 
t-tests, and p-values. 

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``anova`` 
(</span>
``MODELNAME)`` 

</span>

margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Generatesthe ANOVA table but  **** . 

</span>

margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Resultsare incorrect if run on the cell-means model since the reduced model under the
null is that the mean of all the observations is 0!

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``pf(<spanstyle='color:red'>
FSTATISTIC`` , df1=<span style='color:red'>
NUMDF</span>
, df2=<spanstyle='color:red'>
DENDF</span>
, lower. tail=F)

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Findsthe p-value for an observed *F*-statisticwith NUMDF and DENDF degrees of freedom. 

</span>

<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
?</span>
</span>
``par(mfrow=c(2, 2)); plot(<spanstyle='color:red'>
MODELNAME`` )

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Generatesfour diagnostic plots including the Residuals vs Fitted and Normal Q-Q plot. 

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``plot(allEffects(<spanstyle='color:red'>
MODELNAME`` ))</span>


</span>

margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Plotsthe estimated model component. 

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Requiresthe </span>

 package be loaded. 

</span>


<![if !supportLists]>
<spanstyle='font-size:12. 0pt;line-height:115%;font-family:Symbol;mso-fareast-font-family:
Symbol;mso-bidi-font-family:Symbol'>
?<spanstyle='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
</span>
</span>
<![endif]>
``Tm2&lt;-glht(<spanstyle='color:red'>
MODELNAME`` , linfct=mcp(<span style='color:red'>
X</span>
="Tukey");confint(Tm2); plot(Tm2); cld(Tm2)</span>



</span>

margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Requiresthe </span>

 package to be installed and loaded. 

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Canonly be run on the reference-coded version of the model. 

</span>


margin-bottom:6. 0pt;margin-left:1. 0in;mso-add-space:auto;text-indent:-. 25in;style='font-size:12. 0pt;line-height:115%;font-family:"Courier New";mso-fareast-font-family:"Courier New"'>
o<span style='font:7. 0pt "Times New Roman"'>
&nbsp;&nbsp;</span>
</span>
</span>
<![endif]>
Generatesthe text output and plot for Tukey?s HSD as well as the compact letter display. 

</span>


<h2 style='margin-left:0in;text-indent:0in;mso-list:l2 level2 lfo1'>
<a
name="_Toc459020895">
2. 9: Practice problems</a>


</h2>


For thesepractice problems, you will work with the cholesterol data set from the </span>

style='font-size:12. 0pt;mso-bidi-font-size:10. 0pt;line-height:107%;font-family:"Lucida Console"'>
multcomp</span>

 package that was used to generate the Tukey?s HSDresults. To load the data set and learn more about the study, use the following
code:

</span>


style='font-size:12. 0pt;mso-bidi-font-size:10. 0pt;line-height:107%;font-family:"Lucida Console"'>
require(multcomp)

</span>


style='font-size:12. 0pt;mso-bidi-font-size:10. 0pt;line-height:107%;font-family:"Lucida Console"'>
data(cholesterol)

</span>


style='font-size:12. 0pt;mso-bidi-font-size:10. 0pt;line-height:107%;font-family:"Lucida Console"'>
help(cholesterol)

</span>


2. 1. 
Graphically explore the differences in the changes in Cholesterol levels for
the five levels using boxplots and beanplots. 

</span>


2. 2. Is the
design balanced? 

</span>


2. 3. 
Complete all 6+ steps of the hypothesis test using the parametric *F*-test, reporting the ANOVA table andthe distribution of the test statistic under the null. 

</span>


2. 4. 
Discuss the scope of inference using the information that the treatment levels
were randomly assigned to volunteers in the study. 

</span>


2. 5. Generate
the permutation distribution and find the p-value. Compare the parametric
p-value to the permutation test results. 

</span>


2. 6. 
Perform Tukey?s HSD on the data set. Discuss the results ? which pairs were
detected as different and which were not? Bigger reductions in cholesterol are
good, so are there any levels you would recommend or that might provide similar
reductions?

</span>


2. 7. Find and
interpret the CLD and compare that to your interpretation of results from 2. 6. 

</span>


</div>


<hr align=left size=1 width="33%">


<![endif]>


<div style='mso-element:footnote' id=ftn1>


<a style='mso-footnote-id:ftn1' href="#_ftnref1"name="_ftn1" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[1]</span>
</span>
<![endif]>
</span>
</span>
</a>




</div>


<div style='mso-element:footnote' id=ftn2>


<a style='mso-footnote-id:ftn2' href="#_ftnref2"name="_ftn2" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[2]</span>
</span>
<![endif]>
</span>
</span>
</a>





</div>


<div style='mso-element:footnote' id=ftn3>


<a style='mso-footnote-id:ftn3' href="#_ftnref3"name="_ftn3" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[3]</span>
</span>
<![endif]>
</span>
</span>
</a>
 



</div>


<div style='mso-element:footnote' id=ftn4>


<a style='mso-footnote-id:ftn4' href="#_ftnref4"name="_ftn4" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[4]</span>
</span>
<![endif]>
</span>
</span>
</a>
 



</div>


<div style='mso-element:footnote' id=ftn5>


<a style='mso-footnote-id:ftn5' href="#_ftnref5"name="_ftn5" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[5]</span>
</span>
<![endif]>
</span>
</span>
</a>





</div>


<div style='mso-element:footnote' id=ftn6>


<a style='mso-footnote-id:ftn6' href="#_ftnref6"name="_ftn6" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[6]</span>
</span>
<![endif]>
</span>
</span>
</a>

 



</div>


<div style='mso-element:footnote' id=ftn7>


<a style='mso-footnote-id:ftn7' href="#_ftnref7"name="_ftn7" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[7]</span>
</span>
<![endif]>
</span>
</span>
</a>
 


</div>


<div style='mso-element:footnote' id=ftn8>


<a style='mso-footnote-id:ftn8' href="#_ftnref8"name="_ftn8" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[8]</span>
</span>
<![endif]>
</span>
</span>
</a>
 



</div>


<div style='mso-element:footnote' id=ftn9>


<a style='mso-footnote-id:ftn9' href="#_ftnref9"name="_ftn9" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[9]</span>
</span>
<![endif]>
</span>
</span>
</a>





</div>


<div style='mso-element:footnote' id=ftn10>


<a style='mso-footnote-id:ftn10' href="#_ftnref10"name="_ftn10" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[10]</span>
</span>
<![endif]>
</span>
</span>
</a>

 



</div>


<div style='mso-element:footnote' id=ftn11>


<a style='mso-footnote-id:ftn11' href="#_ftnref11"name="_ftn11" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[11]</span>
</span>
<![endif]>
</span>
</span>
</a>





</div>


<div style='mso-element:footnote' id=ftn12>


<a style='mso-footnote-id:ftn12' href="#_ftnref12"name="_ftn12" title="">
<span style='mso-special-character:style='font-size:10. 0pt;line-height:107%;font-family:"Times New Roman", serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>
[12]</span>
</span>
<![endif]>
</span>
</span>
</a>
 



</div>


</div>


** 

</html>

